apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homework-pvc
spec:
  storageClassName: "homework-storageclass"
  resources:
    requests:
      storage: 1G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
