apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  1024;
    }
    http {
      server {
          listen       8000;
          server_name  localhost;
          location / {
            root   /homework; 
            index  index.html index.htm;
        }
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      initContainers:
        - name: init
          image: busybox
          command:
            - "/bin/sh"
            - "-c"
            - "touch /init/index.html; echo '<html><body><title>OTUS: Homework № 4 </title></body></html>' > /init/index.html"
          volumeMounts:
            - mountPath: /init
              name: data
      containers:
        - name: my-web
          image: nginx
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /homework
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
            - name: new-configmap
              mountPath: /homework/conf
          readinessProbe:
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: "index.html"
              port: 8000
          lifecycle:
            preStop:
              exec:
                command: [ 'sh','-c', 'rm -rf /homework/index.html' ]
      nodeSelector:
        homework: 'true'
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: homework-pvc
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: new-configmap
          configMap:
            name: random-configmap
