apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  1024;
    }
    http {
      server {
          listen       8000;
          server_name  localhost;
          location / {
            root   /homework; 
            index  index.html index.htm;
        }
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: homework
  namespace: homework
spec:
  initContainers:
    - name: init
      image: busybox
      command:
        - "/bin/sh"
        -  "-c"
        - "touch /init/index.html; echo '<html><body><title>OTUS: Homework № 1 </title></body></html>' > /init/index.html"
      volumeMounts:
        - mountPath: /init
          name: data
  containers:
    - name: my-web
      image: nginx
      ports:
        - containerPort: 8000
      volumeMounts:
        - mountPath: /homework
          name: data
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      lifecycle:
        preStop:
          exec:
            command: ['sh','-c', 'rm -rf /homework/index.html']
  volumes:
    - name: data
      emptyDir: {}
    - name: nginx-conf
      configMap:
        name: nginx-conf
        items:
          - key: nginx.conf
            path: nginx.conf
